/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package downloadsorter.GUI;

import downloadsorter.FileSorter;
import downloadsorter.Filters.Filter;
import downloadsorter.Settings;
import downloadsorter.SettingsManager;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author Eric
 */
public class MainGUI extends javax.swing.JFrame implements Runnable {
    SettingsManager settings;
    JFileChooser fileChooser;
    /**
     * Creates new form MainGUI
     */
    public MainGUI(SettingsManager s) {
        settings = s;
        fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        btnSaveAndExit = new javax.swing.JButton();
        selectedFilterPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        sourceLabel = new javax.swing.JLabel();
        sourceSelector = new javax.swing.JComboBox<>();
        sourceTextField = new javax.swing.JTextField();
        browseSourceButton = new javax.swing.JButton();
        filterLabel = new javax.swing.JLabel();
        filterSelector = new javax.swing.JComboBox<>();
        destinationLabel = new javax.swing.JLabel();
        destinationSelector = new javax.swing.JComboBox<>();
        destinationTextField = new javax.swing.JTextField();
        browseDestinationButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        filterList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startButton.setText("Run");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        btnSaveAndExit.setText("Save & Exit");
        btnSaveAndExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAndExitActionPerformed(evt);
            }
        });

        nameLabel.setText("Filter Name:");

        nameTextField.setText("New filter");

        sourceLabel.setText("Select Source Rule:");

        sourceSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select source", "Directory" }));

        sourceTextField.setText("select source directory");

        browseSourceButton.setText("Browse");
        browseSourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseSourceButtonActionPerformed(evt);
            }
        });

        filterLabel.setText("Select Filter Rule:");

        filterSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select filter rule", "Anime Fansub" }));

        destinationLabel.setText("Select Destination Rule:");

        destinationSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select destination", "Named Directories" }));

        destinationTextField.setText("select destination directory");

        browseDestinationButton.setText("Browse");

        javax.swing.GroupLayout selectedFilterPanelLayout = new javax.swing.GroupLayout(selectedFilterPanel);
        selectedFilterPanel.setLayout(selectedFilterPanelLayout);
        selectedFilterPanelLayout.setHorizontalGroup(
            selectedFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectedFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectedFilterPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(selectedFilterPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(selectedFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceLabel)
                            .addComponent(filterLabel)
                            .addComponent(destinationLabel)
                            .addGroup(selectedFilterPanelLayout.createSequentialGroup()
                                .addGroup(selectedFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(destinationSelector, javax.swing.GroupLayout.Alignment.LEADING, 0, 172, Short.MAX_VALUE)
                                    .addComponent(filterSelector, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sourceSelector, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(selectedFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sourceTextField)
                                    .addComponent(destinationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(selectedFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(browseSourceButton)
                                    .addComponent(browseDestinationButton))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        selectedFilterPanelLayout.setVerticalGroup(
            selectedFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectedFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sourceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectedFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseSourceButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destinationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectedFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseDestinationButton))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        filterList.setModel(getFilterModel());
        filterList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterListMouseClicked(evt);
            }
        });
        filterList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                filterListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(filterList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(startButton)
                .addGap(71, 71, 71)
                .addComponent(btnSaveAndExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectedFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(btnSaveAndExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        Settings inits = new Settings(settings);
        FileSorter sortingLoop = new FileSorter(inits);
        Thread sortLoop = new Thread(sortingLoop);
        sortLoop.start();
    }//GEN-LAST:event_startButtonActionPerformed

    private void btnSaveAndExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAndExitActionPerformed
        settings.writeSettingsFile();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnSaveAndExitActionPerformed

    private void browseSourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseSourceButtonActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        String sourcePath = fileChooser.getSelectedFile().toString();
        sourceTextField.setText(sourcePath);
    }//GEN-LAST:event_browseSourceButtonActionPerformed

    private void filterListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_filterListValueChanged
        Filter selectedFilter = filterList.getSelectedValue();
        displayFilterInFields(selectedFilter);
    }//GEN-LAST:event_filterListValueChanged

    private void filterListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterListMouseClicked
        
    }//GEN-LAST:event_filterListMouseClicked

    private void displayFilterInFields(Filter filter) {
        String filterString = filter.stringForFile();
        String lines[] = filterString.split("\n");
        nameTextField.setText(lines[0]);
        
        String source[] = lines[1].split(",");
        displaySourceRule(source);
        
        String filterRule[] = lines[2].split(",");
        displayFilterRule(filterRule);
        
        String dest[] = lines[3].split(",");
        displayDestinationRule(dest);
        
    }
    
    private void displaySourceRule(String source[]) {
        if("DirectorySource".equals(source[0]))
            sourceSelector.setSelectedItem("Directory");
        
        if(source.length > 1) {
            String dirs ="";
            for(int i = 1; i < source.length; i++) {
                dirs.concat(source[i] + ",");
            }
            sourceTextField.setText(dirs);
        }
    }
    private void displayFilterRule(String filter[]) {
        if("FansubFilter".equals(filter[0]))
            filterSelector.setSelectedItem("Anime Fansub");
        
        if(filter.length > 1) {
            String params = "";
            for (int i= 1; i > filter.length; i++) {
                params.concat(filter[i] + ",");
            }
            //filterTextField.setText(params);
        }
    }
    
    private void displayDestinationRule(String dest[]) {
        if("DestinationNamedDirectories".equals(dest[0]))
            destinationSelector.setSelectedItem("Named Directories");
        
        if(dest.length > 1) {
            String dirs ="";
            for(int i = 1; i < dest.length; i++) {
                dirs.concat(dest[i] + ",");
            }
            destinationTextField.setText(dirs);
        }
    }
    
    public Filter[] getFilterArray() {
        List<Filter> lf = settings.getSettings().getFilters();
        Filter[] af = new Filter[lf.size()];
        for (int i = 0; i < lf.size(); i++)
            af[i] = lf.get(i);
        return af;
    }
    
    public DefaultListModel getFilterModel() {
        DefaultListModel dlm = new DefaultListModel();
        List<Filter> lf = settings.getSettings().getFilters(); 
        for (Filter f : lf)
            dlm.addElement(f);
        return dlm;
    }

//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

    @Override
    public void run() {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseDestinationButton;
    private javax.swing.JButton browseSourceButton;
    private javax.swing.JButton btnSaveAndExit;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JComboBox<String> destinationSelector;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JList<Filter> filterList;
    private javax.swing.JComboBox<String> filterSelector;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel selectedFilterPanel;
    private javax.swing.JLabel sourceLabel;
    private javax.swing.JComboBox<String> sourceSelector;
    private javax.swing.JTextField sourceTextField;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}